name: week2_dashboard
description: "Week 2 - Declarative UI & Responsive Design (Academic Overview) - M.Adhitya Yusuf Al-Ayyubi TI-2H 244107020045."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
